spring:
  jms:
    listener:
      concurrency: 3-10
    pub-sub-domain: false

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    conn-name: localhost(1414)
    user: admin
    password: passw0rd
    queue:
      request: DEV.QUEUE.1
      reply: DEV.QUEUE.2
